-- =============================================================
-- SCORPION - MIGRACION DE FORMATO
--   * Fechas: TIMESTAMP(0) WITH TIME ZONE  ->  "2026-04-18 20:17:05"
--   * Valores: BIGINT (enteros)            ->  sin ".00"
--
-- CONSERVA LOS DATOS QUE YA TIENES.
-- Solo cambia el tipo de las columnas, redondea a entero los valores
-- y trunca los segundos a 0 milisegundos.
-- =============================================================

BEGIN;

-- -------------------------------------------------------------
-- 1) BORRAR VISTAS (dependen de las columnas que vamos a alterar)
-- -------------------------------------------------------------
DROP VIEW IF EXISTS public."VW_INVENTARIO" CASCADE;
DROP VIEW IF EXISTS public."VW_CAJA"       CASCADE;
DROP VIEW IF EXISTS public."VW_RETIROS"    CASCADE;
DROP VIEW IF EXISTS public."VW_XALE"       CASCADE;
DROP VIEW IF EXISTS public."VW_DEV"        CASCADE;
DROP VIEW IF EXISTS public."VW_VENDIDO"    CASCADE;
DROP VIEW IF EXISTS public."VW_GUARDADERO" CASCADE;
DROP VIEW IF EXISTS public."VW_HISTORIAL"  CASCADE;
DROP VIEW IF EXISTS public."VW_BAR"        CASCADE;
DROP VIEW IF EXISTS public."VW_SALIDAS"    CASCADE;
DROP VIEW IF EXISTS public."VW_GASTOS"     CASCADE;

-- -------------------------------------------------------------
-- 2) CAJA: quitar la columna calculada antes de alterar tipos
-- -------------------------------------------------------------
ALTER TABLE public."CAJA" DROP COLUMN IF EXISTS "CUADRE CAJA";

-- -------------------------------------------------------------
-- 3) INVENTARIO
-- -------------------------------------------------------------
ALTER TABLE public."INVENTARIO"
  ALTER COLUMN "FECHA"        TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA INT"    TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA ABON"   TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA RETIRO" TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA AU"     TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "VR PR"  TYPE BIGINT USING ROUND(COALESCE("VR PR",0))::bigint,
  ALTER COLUMN "VR RT"  TYPE BIGINT USING ROUND(COALESCE("VR RT",0))::bigint,
  ALTER COLUMN "VR IN"  TYPE BIGINT USING ROUND(COALESCE("VR IN",0))::bigint,
  ALTER COLUMN "TOT IN" TYPE BIGINT USING ROUND(COALESCE("TOT IN",0))::bigint,
  ALTER COLUMN "VR AB"  TYPE BIGINT USING ROUND(COALESCE("VR AB",0))::bigint,
  ALTER COLUMN "DES"    TYPE BIGINT USING ROUND(COALESCE("DES",0))::bigint,
  ALTER COLUMN "TOTAL"  TYPE BIGINT USING ROUND(COALESCE("TOTAL",0))::bigint,
  ALTER COLUMN "UTIL"   TYPE BIGINT USING ROUND(COALESCE("UTIL",0))::bigint;

ALTER TABLE public."INVENTARIO"
  ALTER COLUMN "VR PR"  SET DEFAULT 0,
  ALTER COLUMN "VR RT"  SET DEFAULT 0,
  ALTER COLUMN "VR IN"  SET DEFAULT 0,
  ALTER COLUMN "TOT IN" SET DEFAULT 0,
  ALTER COLUMN "VR AB"  SET DEFAULT 0,
  ALTER COLUMN "DES"    SET DEFAULT 0,
  ALTER COLUMN "TOTAL"  SET DEFAULT 0,
  ALTER COLUMN "UTIL"   SET DEFAULT 0;

-- -------------------------------------------------------------
-- 4) CAJA
-- -------------------------------------------------------------
ALTER TABLE public."CAJA"
  ALTER COLUMN "FECHA"     TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "BASE"      TYPE BIGINT USING ROUND(COALESCE("BASE",0))::bigint,
  ALTER COLUMN "RETIRO"    TYPE BIGINT USING ROUND(COALESCE("RETIRO",0))::bigint,
  ALTER COLUMN "GUARDA"    TYPE BIGINT USING ROUND(COALESCE("GUARDA",0))::bigint,
  ALTER COLUMN "BAR"       TYPE BIGINT USING ROUND(COALESCE("BAR",0))::bigint,
  ALTER COLUMN "CONTRATOS" TYPE BIGINT USING ROUND(COALESCE("CONTRATOS",0))::bigint,
  ALTER COLUMN "GASTOS"    TYPE BIGINT USING ROUND(COALESCE("GASTOS",0))::bigint,
  ALTER COLUMN "VENTAS"    TYPE BIGINT USING ROUND(COALESCE("VENTAS",0))::bigint;

ALTER TABLE public."CAJA"
  ALTER COLUMN "BASE"      SET DEFAULT 0,
  ALTER COLUMN "RETIRO"    SET DEFAULT 0,
  ALTER COLUMN "GUARDA"    SET DEFAULT 0,
  ALTER COLUMN "BAR"       SET DEFAULT 0,
  ALTER COLUMN "CONTRATOS" SET DEFAULT 0,
  ALTER COLUMN "GASTOS"    SET DEFAULT 0,
  ALTER COLUMN "VENTAS"    SET DEFAULT 0;

ALTER TABLE public."CAJA"
  ADD COLUMN "CUADRE CAJA" BIGINT GENERATED ALWAYS AS (
    COALESCE("BASE",0) + COALESCE("RETIRO",0) + COALESCE("GUARDA",0) +
    COALESCE("BAR",0) + COALESCE("VENTAS",0)
    - COALESCE("CONTRATOS",0) - COALESCE("GASTOS",0)
  ) STORED;

-- -------------------------------------------------------------
-- 5) RETIROS
-- -------------------------------------------------------------
ALTER TABLE public."RETIROS"
  ALTER COLUMN "FECHA"        TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA INT"    TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA ABON"   TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA RETIRO" TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA AU"     TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "VR PR"  TYPE BIGINT USING ROUND(COALESCE("VR PR",0))::bigint,
  ALTER COLUMN "VR RT"  TYPE BIGINT USING ROUND(COALESCE("VR RT",0))::bigint,
  ALTER COLUMN "VR IN"  TYPE BIGINT USING ROUND(COALESCE("VR IN",0))::bigint,
  ALTER COLUMN "TOT IN" TYPE BIGINT USING ROUND(COALESCE("TOT IN",0))::bigint,
  ALTER COLUMN "VR AB"  TYPE BIGINT USING ROUND(COALESCE("VR AB",0))::bigint,
  ALTER COLUMN "DES"    TYPE BIGINT USING ROUND(COALESCE("DES",0))::bigint,
  ALTER COLUMN "TOTAL"  TYPE BIGINT USING ROUND(COALESCE("TOTAL",0))::bigint,
  ALTER COLUMN "UTIL"   TYPE BIGINT USING ROUND(COALESCE("UTIL",0))::bigint;

-- -------------------------------------------------------------
-- 6) XALE / DEV
-- -------------------------------------------------------------
ALTER TABLE public."XALE"
  ALTER COLUMN "FECHA" TYPE TIMESTAMP(0) WITH TIME ZONE;

ALTER TABLE public."DEV"
  ALTER COLUMN "FECHA" TYPE TIMESTAMP(0) WITH TIME ZONE;

-- -------------------------------------------------------------
-- 7) VENDIDO
-- -------------------------------------------------------------
ALTER TABLE public."VENDIDO"
  ALTER COLUMN "FECHA"        TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA INT"    TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA ABON"   TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA RETIRO" TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA AU"     TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA VENTA"  TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "VR PR"       TYPE BIGINT USING ROUND(COALESCE("VR PR",0))::bigint,
  ALTER COLUMN "VR RT"       TYPE BIGINT USING ROUND(COALESCE("VR RT",0))::bigint,
  ALTER COLUMN "VR IN"       TYPE BIGINT USING ROUND(COALESCE("VR IN",0))::bigint,
  ALTER COLUMN "TOT IN"      TYPE BIGINT USING ROUND(COALESCE("TOT IN",0))::bigint,
  ALTER COLUMN "VR AB"       TYPE BIGINT USING ROUND(COALESCE("VR AB",0))::bigint,
  ALTER COLUMN "DES"         TYPE BIGINT USING ROUND(COALESCE("DES",0))::bigint,
  ALTER COLUMN "TOTAL"       TYPE BIGINT USING ROUND(COALESCE("TOTAL",0))::bigint,
  ALTER COLUMN "UTIL"        TYPE BIGINT USING ROUND(COALESCE("UTIL",0))::bigint,
  ALTER COLUMN "VALOR VENTA" TYPE BIGINT USING ROUND(COALESCE("VALOR VENTA",0))::bigint;

-- -------------------------------------------------------------
-- 8) GUARDADERO / BAR
-- -------------------------------------------------------------
ALTER TABLE public."GUARDADERO"
  ALTER COLUMN "MARCA TEMPORAL" TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "VALOR" TYPE BIGINT USING ROUND(COALESCE("VALOR",0))::bigint;

ALTER TABLE public."BAR"
  ALTER COLUMN "MARCA TEMPORAL" TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "VALOR" TYPE BIGINT USING ROUND(COALESCE("VALOR",0))::bigint;

-- -------------------------------------------------------------
-- 9) HISTORIAL
-- -------------------------------------------------------------
ALTER TABLE public."HISTORIAL"
  ALTER COLUMN "FECHA" TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "VALOR" TYPE BIGINT USING ROUND(COALESCE("VALOR",0))::bigint;

-- -------------------------------------------------------------
-- 10) SALIDAS
-- -------------------------------------------------------------
ALTER TABLE public."SALIDAS"
  ALTER COLUMN "FECHA"        TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA INT"    TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA ABON"   TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA RETIRO" TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "FECHA AU"     TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "VR PR"  TYPE BIGINT USING ROUND(COALESCE("VR PR",0))::bigint,
  ALTER COLUMN "VR RT"  TYPE BIGINT USING ROUND(COALESCE("VR RT",0))::bigint,
  ALTER COLUMN "VR IN"  TYPE BIGINT USING ROUND(COALESCE("VR IN",0))::bigint,
  ALTER COLUMN "TOT IN" TYPE BIGINT USING ROUND(COALESCE("TOT IN",0))::bigint,
  ALTER COLUMN "VR AB"  TYPE BIGINT USING ROUND(COALESCE("VR AB",0))::bigint,
  ALTER COLUMN "DES"    TYPE BIGINT USING ROUND(COALESCE("DES",0))::bigint,
  ALTER COLUMN "TOTAL"  TYPE BIGINT USING ROUND(COALESCE("TOTAL",0))::bigint,
  ALTER COLUMN "UTIL"   TYPE BIGINT USING ROUND(COALESCE("UTIL",0))::bigint;

-- -------------------------------------------------------------
-- 11) GASTOS
-- -------------------------------------------------------------
ALTER TABLE public."GASTOS"
  ALTER COLUMN "FECHA" TYPE TIMESTAMP(0) WITH TIME ZONE,
  ALTER COLUMN "VALOR" TYPE BIGINT USING ROUND(COALESCE("VALOR",0))::bigint;

-- -------------------------------------------------------------
-- 12) VISTAS LIMPIAS (recreadas con los nuevos tipos)
-- -------------------------------------------------------------
CREATE VIEW public."VW_INVENTARIO" AS
SELECT
  "FECHA","OPER","NUMERO","VR PR","VR RT","NOMBRE","CC","ART",
  "DESCRIPCION","LLEVAR","VR IN","TOT IN","FECHA INT","VR AB",
  "FECHA ABON","ESPERA","RETIROS","FECHA RETIRO","DES","AUMENTO",
  "FECHA AU","TOTAL","UTIL"
FROM public."INVENTARIO";

CREATE VIEW public."VW_CAJA" AS
SELECT
  "FECHA","TURNO","BASE","RETIRO","GUARDA","BAR","CONTRATOS",
  "GASTOS","VENTAS","CUADRE CAJA"
FROM public."CAJA";

CREATE VIEW public."VW_RETIROS" AS
SELECT
  "FECHA","OPER","NUMERO","VR PR","VR RT","NOMBRE","CC","ART",
  "DESCRIPCION","LLEVAR","VR IN","TOT IN","FECHA INT","VR AB",
  "FECHA ABON","ESPERA","RETIROS","FECHA RETIRO","DES","AUMENTO",
  "FECHA AU","TOTAL","UTIL"
FROM public."RETIROS";

CREATE VIEW public."VW_XALE" AS
SELECT "ENVIOS","FECHA" FROM public."XALE";

CREATE VIEW public."VW_DEV" AS
SELECT "DEVOLUCIONES","FECHA" FROM public."DEV";

CREATE VIEW public."VW_VENDIDO" AS
SELECT
  "FECHA","OPER","NUMERO","VR PR","VR RT","NOMBRE","CC","ART",
  "DESCRIPCION","LLEVAR","VR IN","TOT IN","FECHA INT","VR AB",
  "FECHA ABON","ESPERA","RETIROS","FECHA RETIRO","DES","AUMENTO",
  "FECHA AU","TOTAL","UTIL","VALOR VENTA","FECHA VENTA"
FROM public."VENDIDO";

CREATE VIEW public."VW_GUARDADERO" AS
SELECT "MARCA TEMPORAL","VALOR" FROM public."GUARDADERO";

CREATE VIEW public."VW_HISTORIAL" AS
SELECT
  "FECHA","OPER","TIPO","NUMERO","NOMBRE","CC","ART",
  "DESCRIPCION","VALOR","DETALLE"
FROM public."HISTORIAL";

CREATE VIEW public."VW_BAR" AS
SELECT "MARCA TEMPORAL","VALOR" FROM public."BAR";

CREATE VIEW public."VW_SALIDAS" AS
SELECT
  "FECHA","OPER","NUMERO","VR PR","VR RT","NOMBRE","CC","ART",
  "DESCRIPCION","LLEVAR","VR IN","TOT IN","FECHA INT","VR AB",
  "FECHA ABON","ESPERA","RETIROS","FECHA RETIRO","DES","AUMENTO",
  "FECHA AU","TOTAL","UTIL"
FROM public."SALIDAS";

CREATE VIEW public."VW_GASTOS" AS
SELECT "FECHA","TURNO","VALOR","DESCRIPCION" FROM public."GASTOS";

COMMIT;
