-- =============================================================
-- SCORPION - REORGANIZACION COMPLETA DE SUPABASE (V2)
-- DESTRUCTIVO: elimina la estructura anterior y crea la nueva.
--
-- IMPORTANTE:
-- 1) Las TABLAS usan nombres iguales a las hojas del Excel, en MAYUSCULAS.
-- 2) Las VISTAS usan prefijo VW_ porque PostgreSQL no permite que
--    una tabla y una vista tengan exactamente el mismo nombre.
-- 3) Este script NO migra datos viejos. Solo crea la nueva estructura.
-- =============================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- -------------------------------------------------------------
-- LIMPIEZA DE VISTAS NUEVAS Y ESTRUCTURA ANTERIOR
-- -------------------------------------------------------------
DROP VIEW IF EXISTS public."VW_INVENTARIO" CASCADE;
DROP VIEW IF EXISTS public."VW_CAJA" CASCADE;
DROP VIEW IF EXISTS public."VW_RETIROS" CASCADE;
DROP VIEW IF EXISTS public."VW_XALE" CASCADE;
DROP VIEW IF EXISTS public."VW_DEV" CASCADE;
DROP VIEW IF EXISTS public."VW_VENDIDO" CASCADE;
DROP VIEW IF EXISTS public."VW_GUARDADERO" CASCADE;
DROP VIEW IF EXISTS public."VW_HISTORIAL" CASCADE;
DROP VIEW IF EXISTS public."VW_BAR" CASCADE;
DROP VIEW IF EXISTS public."VW_SALIDAS" CASCADE;
DROP VIEW IF EXISTS public."VW_GASTOS" CASCADE;

DROP VIEW IF EXISTS public.retiros CASCADE;

DROP TABLE IF EXISTS public.movimientos CASCADE;
DROP TABLE IF EXISTS public.saca CASCADE;
DROP TABLE IF EXISTS public.vendido CASCADE;
DROP TABLE IF EXISTS public.salidas CASCADE;
DROP TABLE IF EXISTS public.xale CASCADE;
DROP TABLE IF EXISTS public.dev CASCADE;
DROP TABLE IF EXISTS public.bar CASCADE;
DROP TABLE IF EXISTS public.guardadero CASCADE;
DROP TABLE IF EXISTS public.gastos CASCADE;
DROP TABLE IF EXISTS public.caja CASCADE;
DROP TABLE IF EXISTS public.empenos CASCADE;
DROP TABLE IF EXISTS public.clientes CASCADE;
DROP TABLE IF EXISTS public.operadores CASCADE;
DROP TABLE IF EXISTS public.tipos_articulo CASCADE;

DROP TABLE IF EXISTS public."INVENTARIO" CASCADE;
DROP TABLE IF EXISTS public."CAJA" CASCADE;
DROP TABLE IF EXISTS public."RETIROS" CASCADE;
DROP TABLE IF EXISTS public."XALE" CASCADE;
DROP TABLE IF EXISTS public."DEV" CASCADE;
DROP TABLE IF EXISTS public."VENDIDO" CASCADE;
DROP TABLE IF EXISTS public."GUARDADERO" CASCADE;
DROP TABLE IF EXISTS public."HISTORIAL" CASCADE;
DROP TABLE IF EXISTS public."BAR" CASCADE;
DROP TABLE IF EXISTS public."SALIDAS" CASCADE;
DROP TABLE IF EXISTS public."GASTOS" CASCADE;

DROP FUNCTION IF EXISTS public.update_updated_at() CASCADE;
DROP FUNCTION IF EXISTS public.obtener_o_crear_caja(date, text) CASCADE;
DROP FUNCTION IF EXISTS public.acumular_caja(date, text, text, numeric) CASCADE;
DROP FUNCTION IF EXISTS public.buscar_empenos_fuzzy(text, integer) CASCADE;

-- -------------------------------------------------------------
-- TABLAS NUEVAS
-- -------------------------------------------------------------
CREATE TABLE public."INVENTARIO" (
  "FECHA" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  "OPER" TEXT,
  "NUMERO" INTEGER NOT NULL CHECK ("NUMERO" BETWEEN 100000 AND 999999),
  "VR PR" BIGINT DEFAULT 0,
  "VR RT" BIGINT DEFAULT 0,
  "NOMBRE" TEXT,
  "CC" TEXT,
  "ART" TEXT,
  "DESCRIPCION" TEXT,
  "LLEVAR" TEXT,
  "VR IN" BIGINT DEFAULT 0,
  "TOT IN" BIGINT DEFAULT 0,
  "FECHA INT" TIMESTAMP(0) WITH TIME ZONE,
  "VR AB" BIGINT DEFAULT 0,
  "FECHA ABON" TIMESTAMP(0) WITH TIME ZONE,
  "ESPERA" TEXT,
  "RETIROS" TEXT,
  "FECHA RETIRO" TIMESTAMP(0) WITH TIME ZONE,
  "DES" BIGINT DEFAULT 0,
  "AUMENTO" TEXT,
  "FECHA AU" TIMESTAMP(0) WITH TIME ZONE,
  "TOTAL" BIGINT DEFAULT 0,
  "UTIL" BIGINT DEFAULT 0,
  CONSTRAINT "PK_INVENTARIO" PRIMARY KEY ("NUMERO")
);

CREATE TABLE public."CAJA" (
  "FECHA" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  "TURNO" TEXT NOT NULL,
  "BASE" BIGINT DEFAULT 0,
  "RETIRO" BIGINT DEFAULT 0,
  "GUARDA" BIGINT DEFAULT 0,
  "BAR" BIGINT DEFAULT 0,
  "CONTRATOS" BIGINT DEFAULT 0,
  "GASTOS" BIGINT DEFAULT 0,
  "VENTAS" BIGINT DEFAULT 0,
  "CUADRE CAJA" BIGINT GENERATED ALWAYS AS (
    COALESCE("BASE", 0) + COALESCE("RETIRO", 0) + COALESCE("GUARDA", 0) +
    COALESCE("BAR", 0) + COALESCE("VENTAS", 0)
    - COALESCE("CONTRATOS", 0) - COALESCE("GASTOS", 0)
  ) STORED
);

CREATE TABLE public."RETIROS" (
  "FECHA" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  "OPER" TEXT,
  "NUMERO" INTEGER NOT NULL CHECK ("NUMERO" BETWEEN 100000 AND 999999),
  "VR PR" BIGINT DEFAULT 0,
  "VR RT" BIGINT DEFAULT 0,
  "NOMBRE" TEXT,
  "CC" TEXT,
  "ART" TEXT,
  "DESCRIPCION" TEXT,
  "LLEVAR" TEXT,
  "VR IN" BIGINT DEFAULT 0,
  "TOT IN" BIGINT DEFAULT 0,
  "FECHA INT" TIMESTAMP(0) WITH TIME ZONE,
  "VR AB" BIGINT DEFAULT 0,
  "FECHA ABON" TIMESTAMP(0) WITH TIME ZONE,
  "ESPERA" TEXT,
  "RETIROS" TEXT,
  "FECHA RETIRO" TIMESTAMP(0) WITH TIME ZONE,
  "DES" BIGINT DEFAULT 0,
  "AUMENTO" TEXT,
  "FECHA AU" TIMESTAMP(0) WITH TIME ZONE,
  "TOTAL" BIGINT DEFAULT 0,
  "UTIL" BIGINT DEFAULT 0,
  CONSTRAINT "PK_RETIROS" PRIMARY KEY ("NUMERO")
);

CREATE TABLE public."XALE" (
  "ENVIOS" INTEGER NOT NULL CHECK ("ENVIOS" BETWEEN 100000 AND 999999),
  "FECHA" TIMESTAMP(0) WITH TIME ZONE NOT NULL
);

CREATE TABLE public."DEV" (
  "DEVOLUCIONES" INTEGER NOT NULL CHECK ("DEVOLUCIONES" BETWEEN 100000 AND 999999),
  "FECHA" TIMESTAMP(0) WITH TIME ZONE NOT NULL
);

CREATE TABLE public."VENDIDO" (
  "FECHA" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  "OPER" TEXT,
  "NUMERO" INTEGER NOT NULL CHECK ("NUMERO" BETWEEN 100000 AND 999999),
  "VR PR" BIGINT DEFAULT 0,
  "VR RT" BIGINT DEFAULT 0,
  "NOMBRE" TEXT,
  "CC" TEXT,
  "ART" TEXT,
  "DESCRIPCION" TEXT,
  "LLEVAR" TEXT,
  "VR IN" BIGINT DEFAULT 0,
  "TOT IN" BIGINT DEFAULT 0,
  "FECHA INT" TIMESTAMP(0) WITH TIME ZONE,
  "VR AB" BIGINT DEFAULT 0,
  "FECHA ABON" TIMESTAMP(0) WITH TIME ZONE,
  "ESPERA" TEXT,
  "RETIROS" TEXT,
  "FECHA RETIRO" TIMESTAMP(0) WITH TIME ZONE,
  "DES" BIGINT DEFAULT 0,
  "AUMENTO" TEXT,
  "FECHA AU" TIMESTAMP(0) WITH TIME ZONE,
  "TOTAL" BIGINT DEFAULT 0,
  "UTIL" BIGINT DEFAULT 0,
  "VALOR VENTA" BIGINT DEFAULT 0,
  "FECHA VENTA" TIMESTAMP(0) WITH TIME ZONE,
  CONSTRAINT "PK_VENDIDO" PRIMARY KEY ("NUMERO")
);

CREATE TABLE public."GUARDADERO" (
  "MARCA TEMPORAL" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  "VALOR" BIGINT NOT NULL DEFAULT 0,
  "NOMBRE" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE public."HISTORIAL" (
  "FECHA" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  "OPER" TEXT,
  "TIPO" TEXT NOT NULL,
  "NUMERO" INTEGER,
  "NOMBRE" TEXT,
  "CC" TEXT,
  "ART" TEXT,
  "DESCRIPCION" TEXT,
  "VALOR" BIGINT,
  "DETALLE" TEXT
);

CREATE TABLE public."BAR" (
  "MARCA TEMPORAL" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  "VALOR" BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE public."SALIDAS" (
  "FECHA" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  "OPER" TEXT,
  "NUMERO" INTEGER NOT NULL CHECK ("NUMERO" BETWEEN 100000 AND 999999),
  "VR PR" BIGINT DEFAULT 0,
  "VR RT" BIGINT DEFAULT 0,
  "NOMBRE" TEXT,
  "CC" TEXT,
  "ART" TEXT,
  "DESCRIPCION" TEXT,
  "LLEVAR" TEXT,
  "VR IN" BIGINT DEFAULT 0,
  "TOT IN" BIGINT DEFAULT 0,
  "FECHA INT" TIMESTAMP(0) WITH TIME ZONE,
  "VR AB" BIGINT DEFAULT 0,
  "FECHA ABON" TIMESTAMP(0) WITH TIME ZONE,
  "ESPERA" TEXT,
  "RETIROS" TEXT,
  "FECHA RETIRO" TIMESTAMP(0) WITH TIME ZONE,
  "DES" BIGINT DEFAULT 0,
  "AUMENTO" TEXT,
  "FECHA AU" TIMESTAMP(0) WITH TIME ZONE,
  "TOTAL" BIGINT DEFAULT 0,
  "UTIL" BIGINT DEFAULT 0,
  CONSTRAINT "PK_SALIDAS" PRIMARY KEY ("NUMERO")
);

CREATE TABLE public."GASTOS" (
  "FECHA" TIMESTAMP(0) WITH TIME ZONE NOT NULL,
  "TURNO" TEXT,
  "VALOR" BIGINT NOT NULL DEFAULT 0,
  "DESCRIPCION" TEXT
);

-- -------------------------------------------------------------
-- RESTRICCIONES / INDICES SIN COLUMNAS TECNICAS
-- -------------------------------------------------------------
CREATE UNIQUE INDEX "UX_CAJA_FECHA_TURNO"
  ON public."CAJA" ("FECHA", "TURNO");

CREATE INDEX "IX_XALE_ENVIO" ON public."XALE" ("ENVIOS");
CREATE INDEX "IX_XALE_FECHA" ON public."XALE" ("FECHA");

CREATE INDEX "IX_DEV_DEVOLUCIONES" ON public."DEV" ("DEVOLUCIONES");
CREATE INDEX "IX_DEV_FECHA" ON public."DEV" ("FECHA");

CREATE UNIQUE INDEX "UX_BAR_FECHA_VALOR"
  ON public."BAR" ("MARCA TEMPORAL", "VALOR");

CREATE UNIQUE INDEX "UX_GUARDADERO_FECHA_VALOR"
  ON public."GUARDADERO" ("MARCA TEMPORAL", "VALOR");

CREATE UNIQUE INDEX "UX_GASTOS_CLAVE_NATURAL"
  ON public."GASTOS" ("FECHA", "TURNO", "VALOR", "DESCRIPCION");

CREATE INDEX "IX_INVENTARIO_FECHA" ON public."INVENTARIO" ("FECHA");
CREATE INDEX "IX_INVENTARIO_OPER" ON public."INVENTARIO" ("OPER");
CREATE INDEX "IX_INVENTARIO_CC" ON public."INVENTARIO" ("CC");
CREATE INDEX "IX_INVENTARIO_RETIROS" ON public."INVENTARIO" ("RETIROS");
CREATE INDEX "IX_INVENTARIO_NOMBRE_TRGM" ON public."INVENTARIO" USING gin ("NOMBRE" gin_trgm_ops);

CREATE INDEX "IX_SALIDAS_FECHA" ON public."SALIDAS" ("FECHA");
CREATE INDEX "IX_VENDIDO_FECHA" ON public."VENDIDO" ("FECHA");
CREATE INDEX "IX_HISTORIAL_FECHA" ON public."HISTORIAL" ("FECHA");
CREATE INDEX "IX_HISTORIAL_OPER" ON public."HISTORIAL" ("OPER");
CREATE INDEX "IX_HISTORIAL_TIPO" ON public."HISTORIAL" ("TIPO");
CREATE INDEX "IX_HISTORIAL_NUMERO" ON public."HISTORIAL" ("NUMERO");
CREATE INDEX "IX_HISTORIAL_NOMBRE_TRGM" ON public."HISTORIAL" USING gin ("NOMBRE" gin_trgm_ops);

-- -------------------------------------------------------------
-- VISTAS LIMPIAS
-- -------------------------------------------------------------
CREATE VIEW public."VW_INVENTARIO" AS
SELECT
  "FECHA", "OPER", "NUMERO", "VR PR", "VR RT", "NOMBRE", "CC", "ART",
  "DESCRIPCION", "LLEVAR", "VR IN", "TOT IN", "FECHA INT", "VR AB",
  "FECHA ABON", "ESPERA", "RETIROS", "FECHA RETIRO", "DES", "AUMENTO",
  "FECHA AU", "TOTAL", "UTIL"
FROM public."INVENTARIO";

CREATE VIEW public."VW_CAJA" AS
SELECT
  "FECHA", "TURNO", "BASE", "RETIRO", "GUARDA", "BAR", "CONTRATOS",
  "GASTOS", "VENTAS", "CUADRE CAJA"
FROM public."CAJA";

CREATE VIEW public."VW_RETIROS" AS
SELECT
  "FECHA", "OPER", "NUMERO", "VR PR", "VR RT", "NOMBRE", "CC", "ART",
  "DESCRIPCION", "LLEVAR", "VR IN", "TOT IN", "FECHA INT", "VR AB",
  "FECHA ABON", "ESPERA", "RETIROS", "FECHA RETIRO", "DES", "AUMENTO",
  "FECHA AU", "TOTAL", "UTIL"
FROM public."RETIROS";

CREATE VIEW public."VW_XALE" AS
SELECT "ENVIOS", "FECHA"
FROM public."XALE";

CREATE VIEW public."VW_DEV" AS
SELECT "DEVOLUCIONES", "FECHA"
FROM public."DEV";

CREATE VIEW public."VW_VENDIDO" AS
SELECT
  "FECHA", "OPER", "NUMERO", "VR PR", "VR RT", "NOMBRE", "CC", "ART",
  "DESCRIPCION", "LLEVAR", "VR IN", "TOT IN", "FECHA INT", "VR AB",
  "FECHA ABON", "ESPERA", "RETIROS", "FECHA RETIRO", "DES", "AUMENTO",
  "FECHA AU", "TOTAL", "UTIL", "VALOR VENTA", "FECHA VENTA"
FROM public."VENDIDO";

CREATE VIEW public."VW_GUARDADERO" AS
SELECT "MARCA TEMPORAL", "VALOR", "NOMBRE"
FROM public."GUARDADERO";

CREATE VIEW public."VW_HISTORIAL" AS
SELECT
  "FECHA", "OPER", "TIPO", "NUMERO", "NOMBRE", "CC", "ART",
  "DESCRIPCION", "VALOR", "DETALLE"
FROM public."HISTORIAL";

CREATE VIEW public."VW_BAR" AS
SELECT "MARCA TEMPORAL", "VALOR"
FROM public."BAR";

CREATE VIEW public."VW_SALIDAS" AS
SELECT
  "FECHA", "OPER", "NUMERO", "VR PR", "VR RT", "NOMBRE", "CC", "ART",
  "DESCRIPCION", "LLEVAR", "VR IN", "TOT IN", "FECHA INT", "VR AB",
  "FECHA ABON", "ESPERA", "RETIROS", "FECHA RETIRO", "DES", "AUMENTO",
  "FECHA AU", "TOTAL", "UTIL"
FROM public."SALIDAS";

CREATE VIEW public."VW_GASTOS" AS
SELECT "FECHA", "TURNO", "VALOR", "DESCRIPCION"
FROM public."GASTOS";

COMMIT;
